### ISSUE TITLE
Difference with node-http-signature regarding (request-target)

### ISSUE THREAD

**Issue by vonagam** [adamcin/httpsig-java#5]
As it is seen from those lines:

https://github.com/joyent/node-http-signature/blob/529441d9d04a8ecb296a2a152929332526344673/lib/signer.js#L331

https://github.com/adamcin/httpsig-java/blob/c1351c809340aec422bcb69352e78edbab62aa9d/api/src/main/java/net/adamcin/httpsig/api/RequestContent.java#L207

There is a difference between inclusion of request-target in a signing string.
In joyent implementation they prepend "(request-target): " before value.
In this implementation this is not done.

I think this problem came from inconsistent spec ( https://github.com/joyent/node-http-signature/blob/529441d9d04a8ecb296a2a152929332526344673/http_signing.md ) which references `request-line` (depreceated) in Signing String Composition, but uses `request-target` in examples (one time missing colon).

I think it is better to follow joyent implementation to avoid inconsistency.
What are your thoughts?

**Comment by adamcin** [comment]
Thanks, @vonagam. I haven't been keeping up with the evolution of the spec, so I'm not surprised I missed this change. On the other hand, I'm not surprised that this particular change was made, since I noticed that the HTTP protocol version specifier isn't always present or consistent in Java HTTP client/server APIs. I will implement this ASAP.

**Comment by adamcin** [comment]
Fix included in httpsig-java 1.3.0 release.

**Comment by vonagam** [comment]
Thanks for fast response and your time put into this library.
